### ISSUE TITLE
process manager: revisit clickable link colors

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1021]
right now we have lighter green as default,
ongoing discussion to make hover over darker green (right now it's blue)

**Comment by stacy-hunt** [comment]
Should be quite easy for Anthony to make it go darker green instead of blue, we could ask him to change it for a bit and try it out, see what we think. If we're OK with it then that would simplify the UI scheme.

**Comment by stacy-hunt** [comment]
If we still like it blue (I have a feeling that will still be my preference) then we might have to consider making the buttons go blue on hover. Or decide if we're happy with buttons being an exception, which may be OK. I do like the subtlety of the way the buttons work now because they have a big surface area and you can spot the change, but it might not be so noticable for text. One possible approach is to have one style for assets with a large surface area and another for assets with smaller area.

**Comment by stacy-hunt** [comment]
I made a call on this and changed it to darker green on hover, blue on mouse down. Since this link is actually a button, it seems like it should be consistent with the other buttons. I've created a card and posted a design in it for submission to the styleguide.
