### ISSUE TITLE
Apply Visual Design to License selector manager

### ISSUE THREAD

**Issue by anthonyettinger** [strongloop/strong-arc#1079]
CLI tools will output a message saying to renew X product with Y feature and this command: `slc arc --licenses` which will take you to the strong-arc licensing page

Show a list of all products and features available grouped by product.

We pre-select product and features that user already has a license for.

Allow user to select the features they need access to:

	[x] strong-arc
		[x] composer
		[x] metrics
		[ ] process-manager
		[ ] build-deploy
		[ ] profiler

	[x] agent
		[x] metrics
		[ ] watchdog

	[ ] connectors (greyed out if renewable flag is false)
		[ ] mssql
		[ ] soap
		[ ] oracle

			[submit]
Other options is to automatically do ALL without user intervention.

**Comment by altsang** [comment]
@raymond: @anthonyettinger  - we need to make a decision on licensing renewal flow

- option 1 - explicitly ask the user to check off which license they want to renew/request, we have the UI to support it, but it places the burden on the user and makes the UI more complciated

- option 2 -  for now we find out what products a user does not have and automatically renew and create new key for what's missing, the logic can still be tricky and divided between Arc and the auth service, but makes the UI a R/O screen pretty much

I'm for option 2 - so long as there's a path to start enforcing trial periods

product policy - https://github.com/strongloop/strong-subscription-admin/blob/master/config/products.json

Raymond Feng [10:54 AM]
for option 2, there are two cases: renew all products or renew product by product on demand

Al Tsang [10:54 AM] 
yes good point

Al Tsang [10:54 AM]
in order to renew product on demand...

Al Tsang [10:55 AM]
anthony would need to call the renew service

Raymond Feng [10:55 AM] 
y

Al Tsang [10:55 AM] 
but he would need to look at what has expired in order to do so

**Comment by altsang** [comment]
we're going with option #2

**Comment by altsang** [comment]
@stacy-hunt @anthonyettinger - please consolidate, I'm totally confused...

![image](https://cloud.githubusercontent.com/assets/2261105/6884704/25f4171e-d5b3-11e4-8ad4-694010574f99.png)

Process Manager (?) is solid red fill with white ?

![image](https://cloud.githubusercontent.com/assets/2261105/6884712/66fd480c-d5b3-11e4-9806-c0312e9f7eae.png)

LIcenses shows (?) solid black fill with white ?

![image](https://cloud.githubusercontent.com/assets/2261105/6884719/aeb215ce-d5b3-11e4-9f47-590268737da1.png)

Styleguide shows (?) solid black fill with white ? but the table shows red version?

![image](https://cloud.githubusercontent.com/assets/2261105/6884725/d4e6d0c2-d5b3-11e4-8e85-1725d8285e04.png)

VD comp shows a no fill with black ?

**Comment by stacy-hunt** [comment]
The ones in the Licensing comp should be red, which is a special style for errors. I'll fix that comp. We can possibly consolidate the hollow grey and black ones, I don't think there's a case for both. I'll look through some of our historical designs and decide which is more general purpose. Al, do you want me to involve you in that decision, or just work with Anthony on it?

**Comment by stacy-hunt** [comment]
OK,  License Viewer comp is updated:
https://drive.google.com/folderview?id=0B1FTzkB7697GVEMtUll2LTdCZ0U&usp=sharing

**Comment by altsang** [comment]
I don't need to be involved, please work out with the team thx Stacy

**Comment by stacy-hunt** [comment]
OK will do.

**Comment by anthonyettinger** [comment]
@stacy-hunt the hollow icons are not possible with font icons. That's why its black. I can make it red so its consistent.

**Comment by stacy-hunt** [comment]
Nah, the red ones are only for when there's an error. I looked through the
designs and concluded that the hollow grey ones are best for the general
case because normally it is a secondary feature and I don't want it to have
too much weight. Do we have to use a font icon for it?

**Comment by altsang** [comment]
@stacy-hunt, @anthonyettinger - are we squared away here?

**Comment by anthonyettinger** [comment]
yeah, afaik. @stacy-hunt ?

**Comment by stacy-hunt** [comment]
I thought I already posted this, so if you find it in another card close it. I searched but can't find it.

![image](https://cloud.githubusercontent.com/assets/1924932/6991143/affd122c-dadf-11e4-96f1-a5b20d94ecf6.png)

**Comment by altsang** [comment]
looks good @stacy-hunt - I can seem to find the card for above can you pls create another?

@anthonyettinger - see #1135 for license key viewing UX and VD per our discussion last week

**Comment by anthonyettinger** [comment]
The error icon/size will be addressed in #1119

**Comment by altsang** [comment]
closing this otherwise, verified on master
