### ISSUE TITLE
styleguide: change add-item button style

### ISSUE THREAD

**Issue by jtary** [strongloop/strong-arc#1118]
Change style of "Add Item" link on the bottom of tables to use the defined small-button style, rather than the link-style button currently in use.

**Comment by jtary** [comment]
Justification:

The add item button, when styled as a link, does not immediately present to the user as an action. The increases the cognitive load on the user when operating the page, requiring them to infer that the text is actually a button. We already have a well defined button style, which can be retrofitted quite easily, and solves this issue:

ref: http://uxmovement.com/buttons/when-to-use-a-button-or-link/

Additionally, by using the button-style, it greatly simplifies aligning the button with the table it affects, and integrating it visually with other buttons that affect the table such as save, or revert.

**Comment by altsang** [comment]
agreed on increasing the cognitive load, but I think that's an acceptable tradeoff to making the UI heavy especially for non-persisted actions like bringing up modal windows or adding a table row

we have the logout, help and app controller buttons that could be interpreted as images instead of button as well, but we've forgone the classic button encapsulation there as well

+Add Row - there a bit more intuition with the "+" sign that we're utilizing and I think having buttons for persisting versus buttons for secondary actions makes sense, albeit more progressive

after discussion: @stacy-hunt to add to styleguide under buttons section and create a card to have it implemented and reviewed and then retrofitted to Composer (Properties table) and +Add Host to Process Manager

/cc: @anthonyettinger, @seanbrookes
