### ISSUE TITLE
Add Dialog component to styleguide

### ISSUE THREAD

**Issue by stacy-hunt** [strongloop/strong-arc#1171]
![image](https://cloud.githubusercontent.com/assets/1924932/7057790/e6e210d6-dead-11e4-88e8-fc02efac8a53.png)

**Comment by chandadharap** [comment]
@stacy-hunt  Can this be verified before Monday morning please, I'd like to close out Sprint on Monday.

**Comment by stacy-hunt** [comment]
Yep, there's been a technical issue with me getting a look at it but Joe and I are working to resolve it. I'm sure we'll get it closed by then.

**Comment by stacy-hunt** [comment]
Design Review:

- The corners should be square
- The primary button ("Close" in this case) should be right aligned with the content
      (looks like the difference is caused by the scrollbar)

![image](https://cloud.githubusercontent.com/assets/1924932/7212379/17741b14-e5ba-11e4-990e-181e89a8e7e7.png)

**Comment by jtary** [comment]
The scroll bar issue is pretty much impossible to fix, since every browser/OS has slightly different sized scrollbars, and there is no reliable way of figuring out how much extra padding to leave.  It's a pretty minor issue, and only really noticeable when you have some sort of boxing that shoes where the content edge is. Stacy and I both agreed that it was better for now to just avoid scrolling dialogs where ever we can.

For the square corners, I'll fix that as part of the watchdog UX, since that's where we decided to move them from rounded to square anyways.

**Comment by chandadharap** [comment]
@jtarry Can we close this then?

**Comment by stacy-hunt** [comment]
As long as the corners are fixed. Which card is that issue being recorded in, Joe?
