### ISSUE TITLE
Arc: Spike on Visual Composite Model - backend piece

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#1241]
As a SL developer using Arc, I would want a way to visually compose course grain APIs that client views would directly consume that is made up of microservices models, so that I can service clients more efficiently.

two parts: back end and front end
- [ ] need to augment workspace API so that LB models can be "mixed" into a composite model
- [ ] composite model will only runnable on the StrongLoop Gateway
- [ ] composite models can inherit properties AND  methods

**Comment by ritch** [comment]
@altsang +1 for the way this story is written!  

Here is a brief outline of the tasks I'd expect it would take to complete this feature.

**loopback-gateway**

 - add a new type of model: `CompositeModel`

This ensures the feature is only supported by loopback-gateway and not loopback core. The downside is that you **must** use a gateway in order to do composite API.

**loopback-workspace**

 - We will re-use the `ModelDefinition` API
 - Add basic validation for `CompositeModel` settings.

example `ModelDefinition` might look like this:

```js
{
  base: 'CompositeModel',
  options: {
    http: {path: '/statistics'}
    // this is where the composite model settings / declartion will go
  }
}
```

**arc**

 - create canvas view with support for creating models (pre-requisite, out of scope for this epic)
 - add support to the canvas for creating `CompositeModels`

**Comment by raymondfeng** [comment]
Follow-up stories:

strongloop-internal/scrum-loopback#490
strongloop-internal/scrum-loopback#489
strongloop-internal/scrum-loopback#490
