### ISSUE TITLE
Policies design fixes

### ISSUE THREAD

**Issue by anthonyettinger** [strongloop/strong-arc#1505]
- [x] Policy form - use same components as Pipeline form
- [x] Policy List: Add New Policy button: use the borderles button  from the Styleguide
- [x] New Policy Dialog - make a visual comp
- [x] modal-md styling is off, should like large modal on styelguide but smaller
- [x] Hide “Revert” and “Save” buttons until form is dirty, and place them at the bottom left (see pipeline edit)
- [x] Add “Revert” button to Policy form
- [x] Make forms look like Pipeline forms
- [x] Add Icon to Policy form (dialog and edit, see comp)
- [x] Remove margin from edit forms headings

e2e test
- [x] fix tests that broke with updates

**Comment by chandadharap** [comment]
@stacy-hunt Please verify all except e2e tests before end of Friday if possible.

**Comment by chandadharap** [comment]
ping? is this verified @stacy-hunt?

**Comment by stacy-hunt** [comment]
I'm still having issues getting Anthony's branch running on my computer. I'm hoping to get Sean to help me with it, but everyone's been on holiday. I think we need to find a more designer-friendly way to pull branches and update them. I aways run into issues I can't resolve when I try to do it using the command line. I'll talk to the guys about that in today's meeting.

**Comment by stacy-hunt** [comment]
Here's a visual comp for the New Policy dialog

![image](https://cloud.githubusercontent.com/assets/1924932/9749123/91c7eb74-5636-11e5-9057-361b6cd8a63c.png)

**Comment by stacy-hunt** [comment]
- Policy form - use same components as Pipeline form
- [x] Verified
- Policy List: Add New Policy button: use the borderles button  from the Styleguide
- [x] Verified
- modal-md styling is off, should like large modal on styelguide but smaller
- [x] Verified 
- Hide “Revert” and “Save” buttons until form is dirty,
- [ ] Not verified - they don't seem to be doing this 
-  and place them at the bottom left (see pipeline edit)
- [x] Verified 
- Add “Revert” button to Policy form
- [x] Verified
- Make forms look like Pipeline forms
- [x] Verified
- Add Icon to Policy form (dialog and edit, see comp)
- [x] Verified
- Remove margin from edit forms headings
- [x] Verified

**Comment by stacy-hunt** [comment]
Hey Anthony I assigned this one back to you because I don't think the Revert and Save buttons are hiding until the form is dirty. If you want to break that one out into another card we could mark this one as done?

**Comment by chandadharap** [comment]
Please don't break out into another card. That not a good practice. Leave this open until done.

**Comment by seanbrookes** [comment]
I understood the design was to have the buttons disabled until the data is dirty.  
People find it confusing if they come to change the data and don't see any control buttons.

We had a bug report recently from someone becuase they didn't think there was a way to delete model properties in the composer becuase they didn't know they had to hover over the table to actually show the button.

**Comment by bajtos** [comment]
To be discussed with Stacy today.

**Comment by stacy-hunt** [comment]
Sorry guys I need to pick up my daughter from the airport at 3pm today. I
could do 2pm for 30 mins if that works?

Sean, I think it's more confusing to have a "Revert" and "Save' button on a
page where there is no change to the information, even if they are greyed.
The comps show there are no revert or save buttons until the form is dirty,
so I'm not sure where you got the impression the design was meant to
deviate from that. It's better practice to hide elements until they're
needed rather than having them taking up space and the user's attention
when they don't do anything- unless of course there is a compelling reason
why they should be there. In this case, I don't think that reason is
compelling.

I'd suggest we follow the design unless Sean's objection is deemed to be
substantive enough to warrant user testing and iteration.

S

**Comment by seanbrookes** [comment]
Arc users have experience confusion with our UI because we make primary interface controls invisible by default.

I thought the design called for disabled controls so the user would at least know they could do something to the data at first glance but if the design calls for invisible controls then I was mistaken.

**Comment by anthonyettinger** [comment]
@stacy-hunt -- I hid the buttons until the forms are dirty.

**Comment by stacy-hunt** [comment]
Thank Anthony, I'll touch base to get your branch on my machine for testing.

**Comment by stacy-hunt** [comment]
All checked and verified
