### ISSUE TITLE
Verb selection from drop down not working when creating new mapping

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#1574]
To repro,
create new mapping.
Try to select verb from drop down. 
This doesn't work.

**Comment by anthonyettinger** [comment]
This works, it just is hidden because the menu is too narrow. I'm assigning to @jtary since he has the ticket to fix the responsiveness of that form.

@jtary -- I was wrong, its not a table layout that is the problem, there is some CSS3 flex grid stuff going on which causes it to not respect the width. You're more familiar with flex grid than I am.

**Comment by bajtos** [comment]
This is related to other CSS bugs already scheduled for Sprint 82.

**Comment by cgole** [comment]
verified
