### ISSUE TITLE
cluster size not getting set correctly with deploy

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#582]
on first deploy, arc doesn't set the size correctly, on subsequent deploys, it does.

**Comment by sam-github** [comment]
This is because there is no way to set the size until there is an instance, and there isn't an instance until there is a deploy. Once there is an instance, the size is persistent.

See https://github.com/strongloop-internal/scrum-cs/issues/260

The fix is that strong-deploy should take a size argument, and set the size before doing the deploy, so it all happens at once. This would help arc, because it would become a feature of the strong-deploy API.

The work-around, for CLI, is to:
1. create the service: `sl-meshctl create helo`
2. set the size: `sl-meshctl set-size helo 3`
3. deploy: `sl-deploy -s helo`

(above tested against master... I'm not sure if it will work with 4.x, the size isn't persistent in 4.x)
(5.x should come be end of sprint, in the meantime, deploying with arc using a size of 1 will create a persistent size of 1, all deploys after will use a size of 1)

**Comment by sam-github** [comment]
The reason this isn't trivial, is the size is on the instance model, and no instance exists until a deploy or create-instance has happened. I am pretty sure we'd have to upgrade the mesh models to fix it, and the new mesh models won't work with the old pm inside arc.

**Comment by sam-github** [comment]
would fix https://github.com/strongloop-internal/scrum-cs/issues/260#issuecomment-119269118

**Comment by sam-github** [comment]
also close to fixing https://github.com/strongloop/strong-pm/issues/261, which is another variant of "want to deploy and set something about the same app in one-shot"

**Comment by sam-github** [comment]
Fix is that:

- [ ] sl-deploy should accept a `--size` option, and set the service to that size (if provided) before deploying, so after serviceFindOrCreate(), but before the deploy
- [ ] deploy api should be changed to `require('strong-deploy').deploy(options, callback)`, where the current positional parameters become properties in an options object
- [ ] sl-deploy API in index.js should have a size option added to it
- [ ] strong-arc should be changed to use the new sl-deploy API

**Comment by sam-github** [comment]
@crandmck need doc: `slc deploy` has a --size option now

**Comment by crandmck** [comment]
Updated http://docs.strongloop.com/display/NODE/slc+deploy, with new option currently hidden from external view.  Will make it visible when the change is published to npm.

**Comment by sam-github** [comment]
https://github.com/strongloop-internal/scrum-nodeops/issues/854 doesn't appear to effect strong-pm, but @cgole, you should make very sure!

**Comment by crandmck** [comment]
The doc is updated with `--size` option

**Comment by cgole** [comment]
there is a bug here. I set the cluster size to 3 and deployed my app through arc. My cluster has 4 workers, not including the master worker. Looks like it picking the default no of cpu's as cluster size

Chandrikas-MacBook-Air:~ chandrikagole$ slc ctl
Service ID: 1
Service Name: default
Environment variables:
  No environment variables defined
Instances:
    Version  Agent version  Cluster size  Driver metadata
     5.0.6       2.0.22           4             N/A
Processes:
        ID      PID   WID  Listening Ports  Tracking objects?  CPU profiling?  Tracing?
    1.1.13774  13774   0
    1.1.13775  13775   1     0.0.0.0:3003
    1.1.13776  13776   2     0.0.0.0:3003
    1.1.13777  13777   3     0.0.0.0:3003
    1.1.13778  13778   4     0.0.0.0:3003

**Comment by sam-github** [comment]
@Setogit You applied two PRs to fix this, but @cgole doesn't see it as fixed, PTAL

**Comment by Setogit** [comment]
The two PRs are:
- [ ] strong-deploy (merged to master on Jul 23 by @setogit) : https://github.com/strongloop/strong-deploy/commit/e828da51d47c7c31687fe441398ebac72da5e4e1
- [ ] strong-arc  (merged to master on Jul. 27 by @setogit): https://github.com/strongloop/strong-arc/commit/3a2210a16c05559c69c751247820009e41d2ac76
Then, the strong-arc change was reverted by @kraman on Jul.30.  

It makes sense the fix is not in Arc.  @kraman: Why was it reverted and can we merge it hack to Arc as-is again?

**Comment by seanbrookes** [comment]
is this related to: https://github.com/strongloop-internal/scrum-nodeops/issues/937

- stopping and starting tracing via Arc seems to mess with the cluster size on the pm

**Comment by kraman** [comment]
@seanbrookes @Setogit If i remember right, It was reverted due to API version incompatibility with built-in PM. Deploying to external PM worked fine but local-deploy was failing.

**Comment by Setogit** [comment]
If what @kraman wrote above is the case, our option seems to be:
A. replace the build-in PM with the latest with which the strong-deploy works and re-apply the fix to strong-arc.
or
B. Live with the current broken behavior.

@seanbrookes  What's the level of effort for the option A?

**Comment by seanbrookes** [comment]
I am working on removing the dependency on the interal pm this sprint so we can get rid of it completely afaic

**Comment by Setogit** [comment]
After Sean's work, just re-enable : 3a2210a  in Arc

**Comment by Setogit** [comment]
connect to https://github.com/strongloop/strong-arc/pull/1539

**Comment by chandadharap** [comment]
Internal dependency is removed.

**Comment by Setogit** [comment]
Reverted the revert of 3a2210a

**Comment by cgole** [comment]
verified
