### ISSUE TITLE
getting started II: add a deploy step

### ISSUE THREAD

**Issue by altsang** [strongloop/strong-arc#923]
the intermediate tutorial is great, please add one more step to illustrate how to deploy the app utilizing Arc and reference that you can do the same thing using slc to build and deploy as well.

**Comment by crandmck** [comment]
Since we removed the short section from LB Getting Started that used to talk about resizing clusters (via `slc run --cluster x`), I suggest we gently introduce/cross-reference some NodeOps capabilities from the LB G.S. as follows:
- In [Getting Started (part 1)](http://docs.strongloop.com/display/LB/Getting+started+with+LoopBack) add a new chapter at the end (before "Learn More") that explains how to run the app with `slc start` and briefly describes a few of the cool things you can do with PM.
- In [Getting Started part II](http://docs.strongloop.com/display/LB/Getting+started+part+II) again at the end,  (before "Learn More") add a brief chapter that explains how to deploy to a remote host.

@altsang what do you think?  Is the second item above too much or irrelevant in that context?

**Comment by altsang** [comment]
:+1: makes sense to me, anything to cross promote strong-pm would be good, go for it please

**Comment by crandmck** [comment]
@DeniseLee Let's talk about this.  I think it should be relatively straightforward.

**Comment by DeniseLee** [comment]
@crandmck, these are ready for your review. You might have to modify, but tried to take you as far as I could.  Two pages:
 http://docs.strongloop.com/display/LB/Deploying+your+application  and http://docs.strongloop.com/display/LB/Run+in+a+cluster

**Comment by crandmck** [comment]
@deniselee: I made a few edits to the articles.  I'm going to assign to Al for final review, then we can publish the articles.  Here are answers to your questions.

> Need to make sure there is a step7 in github.

Yes, there's one already: https://github.com/strongloop/loopback-getting-started-intermediate/releases/tag/step7

> The instance of Arc that I brought up did not seem functional.

This is probably because you were using FireFox.

**Comment by crandmck** [comment]
@altsang: PTAL

New article in LoopBack Getting Started: http://docs.strongloop.com/display/LB/Run+in+a+cluster

New article in LBGS II:
http://docs.strongloop.com/display/LB/Deploying+your+application

**Comment by altsang** [comment]
added two comments, thx @crandmck assigning back to you

**Comment by crandmck** [comment]
Incorporated your comments and published the articles.
