### ISSUE TITLE
arc manager : Cannot add second pm host unless previous pm host is activated

### ISSUE THREAD

**Issue by cgole** [strongloop/strong-arc#958]

**Comment by seanbrookes** [comment]
I don't think this is still the case.  Please retest

**Comment by cgole** [comment]
Still doesnt work for me.

**Comment by seanbrookes** [comment]
this doesn't make a lot of sense.

Steps to reproduce?
- add new host / port to manager (not a valid PM host)
- the value should show up as a row in the grid with a 'Problem' status
- you then click 'Add New Host' link at the bottom 
- then what??  - the 'new host' row should open at the bottom of the grid and you should be able to add a host and port and 'activate' to add to the list

What may be happening is some confustion due to the incomplete type-ahead feature.  it currently only shows the local pm instance (partialy masked) from the PID selector on the metrics and profiler views.  It will be less confusing when that is done.

**Comment by cgole** [comment]
reproduced in hangout

**Comment by chandadharap** [comment]
Needs Documentation. @altsang?

**Comment by altsang** [comment]
will work with @crandmck on getting documented:

@seanbrookes please disable the `Add New Host`link using whatever style convention we have, and put a tool tip explaining that the first record must be successfully activated in order to add more hosts
